### ISSUE TITLE
[Setting] 프로젝트 세팅

### ISSUE THREAD

**Issue by devxsby** [devxsby/ios-bank-app#1]
## 🛠 Issue
- Tuist로 Modular Architecture 구현
- 아키텍처 (미정)

## 📝 To-do

- [x] Tuist Helper Function
- [x] Feature Modules ( Splash / Main / Setting_
- [ ] 아키텍처 구조로 폴더링
